// Generated by AI ChatGPT, edited by ArthurVesta
let modalDirection = "right";
function initModals() {
  modalDirection = window.innerWidth <= window.innerHeight ? "right" : "top";
  document.querySelectorAll(".modal").forEach(modal => {
    modal.classList.toggle("dir-right", modalDirection === "right");
    modal.classList.toggle("dir-top", modalDirection === "top");
    if (modalDirection === "right") {
      modal.style.right = "-100%";
      modal.style.top = "0";
    } else {
      modal.style.right = "0";
      modal.style.top = "-100%";
    }
  });
  updateModalFromURL();
}
function openModal(id) {
  const modal = document.getElementById(id);
  if (!modal) return;
  if (window.location.hash !== "#" + id) {
    window.location.hash = id;
  } else {
    updateModalFromURL();
  }
}
function closeModal(id) {
  const modal = document.getElementById(id);
  if (!modal) return;
  if (window.location.hash === "#" + id) {
    history.back();
  } else {
    updateModalFromURL();
  }
}
function updateModalFromURL() {
  const hash = window.location.hash.slice(1);
  document.querySelectorAll(".modal").forEach(modal => {
    const isActive = modal.id === hash;
    if (modalDirection === "right") {
      modal.style.right = isActive ? "0" : "-100%";
      modal.style.top = "0";
    } else {
      modal.style.right = "0";
      modal.style.top = isActive ? "0" : "-100%";
    }
  });
}
window.addEventListener("DOMContentLoaded", initModals);
window.addEventListener("hashchange", updateModalFromURL);